name: tweetnacl
version: 0.3.2

description: Port of TweetNaCl cryptographic library to Dart.
author: Jeff Lee <jspschool@gmail.com>
homepage: https://github.com/jspschool/tweetnacl-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  convert: ^2.0.2

dev_dependencies:
  test: ^1.0.0
